version: '3.5'

services:
  wallaby_db:
    build: .
    image: wallaby_db
    container_name: wallaby_db
    env_file:
      - psql.env
    ports:
      - 5432:5432
    networks:
      - wallaby_network
    volumes:
      - /data:/var/lib/postgresql/data

networks:
  wallaby_network:
    name: wallaby_network
    driver: bridge
